- name: Playbook to invalidate cache from a cloudfront cdn 
  hosts: localhost
  tasks:

  - name: Create Downloads directory
    file:
      path: '/home/{{ ansible_user }}/Downloads'
      state: directory
  - name: Download Prometheus Node Exporter
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz
      dest: '/home/{{ ansible_user }}/Downloads'
      checksum: sha256:8c1f6a317457a658e0ae68ad710f6b4098db2cad10204649b51e3c043aa3e70d
  - name: Extract Node Exporter
    unarchive:
      src: '/home/{{ ansible_user }}/Downloads/node_exporter-1.1.2.linux-amd64.tar.gz'
      dest: '/home/{{ ansible_user }}'
      remote_src: yes
  - name: Create node_exporter user 
    user:
      name: node_exporter
      shell: /bin/false
      create_home: no
    become: yes
  - name: Copy node exporter to /usr/local/bin 
    copy:
      src: '/home/{{ ansible_user }}/node_exporter-1.1.2.linux-amd64/node_exporter'
      dest: /usr/local/bin
      owner: node_exporter
      group: node_exporter
      mode: '0700'
      remote_src: yes
    become: yes
  - name: Download Node Exporter service configuration
    get_url:
      url: https://github.com/JDavidGuzman/ansible-prometheus-node-exporter/raw/master/files/node_exporter.service
      dest: /etc/systemd/system/node_exporter.service
  - name: Start Node Exporter service 
    systemd:
      daemon_reload: yes
      state: started
      enabled: yes
      name: node_exporter
    become: yes